# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnapp
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'
  
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  target 'rnappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
