# Uncomment the next line to define a global platform for your project
ENV["COCOAPODS_DISABLE_STATS"] = "true"

target 'rnapp' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnapp


  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Performance', '~> 5.15.0'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  
  pod 'GoogleAppMeasurement', '5.4'
  
  target 'rnappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
#use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
