# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnapp' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnapp


  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'Firebase/Core'
  pod 'Firebase/Performance'

  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  target 'rnappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
