price_tier 0
app_review_information(
  first_name: "Connor",
  last_name: "Larkin",
  phone_number: "8475659827",
  email_address: "connor.larkin1@gmail.com",
  demo_user: "dev",       # add the user if testers will need to log in
  demo_password: "dev",   # add the password if testers need it
  notes: "Source Code: https://github.com/connorlarkin1/CDA/tree/master/rnapp"
)
# if you app has more complex structure, check out /fastlane/metadata/review_information folder

submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})

automatic_release false

app_icon "./fastlane/metadata/AppIcon.png"

app_rating_config_path "./fastlane/metadata/itunes_rating_config.json"