# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out )
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
      ensure_git_status_clean
      increment_build_number
      commit_version_bump
      add_git_tag
      build_app(
          workspace: "rnapp.xcworkspace",
          scheme: "rnapp",
          clean: true
          )
      upload_to_testflight(
          app_identifier: "com.connorlarkin.CDA"
          )
  end
  
  lane :screenshots do
    capture_screenshots(workspace: "rnapp.xcworkspace", scheme: "FASTLANE SCREENSHOTS", number_of_retries: 3, concurrent_simulators: false)
    frame_screenshots(white: false)
    upload_to_app_store(skip_binary_upload: true, skip_metadata: false)
  end
end
