# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out )
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane
before_all do
  ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/Contents/Developer'
  skip_docs
  update_fastlane
  clear_derived_data
  git_pull
  ensure_git_status_clean
end
default_platform(:ios)

platform :ios do
  lane :beta do
      xcodeproj = "./ios/rnapp.xcodeproj"
      increment_build_number
      add_git_tag
      gym(scheme: "rnapp", workspace: "rnapp.xcworkspace")
      pilot
      push_to_git_remote
  end
  
  lane :screenshots do
    capture_screenshots(workspace: "rnapp.xcworkspace", scheme: "FASTLANE SCREENSHOTS", number_of_retries: 3, concurrent_simulators: false)
    frame_screenshots(white: false)
    upload_to_app_store(skip_binary_upload: true, skip_metadata: false)
  end
end

platform :android do
  # Android Lanes
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end
  
  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
  end
end





